FROM node:22-alpine

WORKDIR /app

COPY packages/server/package.json package.json
RUN npm install --omit=dev

COPY packages/server/dist dist

ENV PORT=4000
EXPOSE 4000
VOLUME ["/data"]

CMD ["npm", "start"]
